[package]
name = "containerd-shim-wasm"
description = "Library for building containerd shims for wasm"
version = "0.2.1"
edition.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
containerd-shim = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
oci-spec = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
protobuf = "3.2"
ttrpc = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
libc = { workspace = true }

[target.'cfg(unix)'.dependencies]
clone3 = "0.2"
caps = "0.5"
command-fds = "0.2"
libcontainer = { workspace = true, optional = true, default-features = false }
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features= [
    "Win32_Foundation", 
    "Win32_System_Threading", 
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_Storage_FileSystem"] }

[build-dependencies]
ttrpc-codegen = { version = "0.4.2", optional = true }

[dev-dependencies]
tempfile = "3"
signal-hook = "0.3"

[features]
default = []
libcontainer_default = ["libcontainer/default"]
generate_bindings = ["ttrpc-codegen"]
generate_doc = []
libseccomp = ["libcontainer/libseccomp"]
systemd = ["libcontainer/systemd"]
cgroupsv2 = ["libcontainer/v2"]
cgroupsv1 = ["libcontainer/v1"]
cgroupsv2_devices = ["libcontainer/cgroupsv2_devices"]
