[package]
name = "containerd-shim-wasm"
description = "Library for building containerd shims for wasm"
version = "0.2.1"
edition.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
containerd-shim = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
oci-spec = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
protobuf = "3.2"
ttrpc = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
libc = { workspace = true }
cap-std = { workspace = true }

[target.'cfg(unix)'.dependencies]
clone3 = "0.2"
caps = "0.5"
command-fds = "0.2"
proc-mounts = "0.3"
cgroups-rs = "0.3.3"
nix = { workspace = true }

[build-dependencies]
ttrpc-codegen = { version = "0.4.2", optional = true }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"
signal-hook = "0.3"
env_logger = { workspace = true }
rand = "0.8"

[features]
default = []
generate_bindings = ["ttrpc-codegen"]
generate_doc = []
