[package]
name = "runwasmtime"
version.workspace = true
edition.workspace = true

[dependencies]
containerd-shim = { workspace = true }
containerd-shim-wasm = { path = "../containerd-shim-wasm" }
log = { workspace = true }
ttrpc = { workspace = true }
wasmtime = "2.0"
wasmtime-wasi = "2.0"
wasi-common = "2.0"
chrono = { workspace = true }
anyhow = { workspace = true }
cap-std = { workspace = true }
oci-spec = { workspace = true, features = ["runtime"] }
thiserror = { workspace = true }
serde_json = { workspace = true }
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = {version = "0.45", features = [ "Win32_Foundation", "Win32_Storage_FileSystem"]}

[dev-dependencies]
tempfile = "3.0"
libc = { workspace = true }
pretty_assertions = "1"

[[bin]]
name = "containerd-shim-wasmtime-v1"
path = "src/bin/containerd-shim-wasmtime-v1/main.rs"

[[bin]]
name = "containerd-shim-wasmtimed-v1"
path = "src/bin/containerd-shim-wasmtimed-v1/main.rs"

[[bin]]
name = "containerd-wasmtimed"
path = "src/bin/containerd-wasmtimed/main.rs"
