name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          rustflags: '' #Disable.  By default this action sets environment variable is set to -D warnings.  We manage this in the Makefile
      - name: Setup OCI runtime build env
        run: |
          os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          ${GITHUB_WORKSPACE}/.github/scripts/build-$os.sh
        shell: bash
      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        run: |
          echo "WASMEDGE_LIB_DIR=C:\Program Files\WasmEdge\lib" >> $env:GITHUB_ENV
          echo "WASMEDGE_INCLUDE_DIR=C:\Program Files\WasmEdge\include" >> $env:GITHUB_ENV
      - name: Run checks
        run: make check
  build:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "check cgroup version"
        run: "mount | grep cgroup"
        if: runner.os == 'Linux'
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUST_CACHE_KEY_OS: ${{ matrix.os }}
        with:
           rustflags: '' #Disable.  By default this action sets environment variable is set to -D warnings.  We manage this in the Makefile
      - name: Setup OCI runtime build env
        run: |
          os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          ${GITHUB_WORKSPACE}/.github/scripts/build-$os.sh
        shell: bash
      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        run: |
          echo "WASMEDGE_LIB_DIR=C:\Program Files\WasmEdge\lib" >> $env:GITHUB_ENV
          echo "WASMEDGE_INCLUDE_DIR=C:\Program Files\WasmEdge\include" >> $env:GITHUB_ENV
      - name: Build
        run: make build
      - name: Validate docs
        run: ./scripts/validate-docs.sh
      - name: Run tests
        run: |
          make test
        if: runner.os == 'Linux' #disable tests on windows until fully supported

  e2e-wasmtime:
    needs: [build]
    strategy:
      matrix:
        # 20.04 uses cgroupv1, 22.04 uses cgroupv2
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "check cgroup version"
        run: "mount | grep cgroup"
      - uses: actions/checkout@v3
      - name: setup rust-wasm target
        run: rustup target add wasm32-wasi
      - name: Setup OCI runtime build env
        run: ${GITHUB_WORKSPACE}/.github/scripts/build-linux.sh
        shell: bash
      - name: run
        run: make test/k8s
      # only runs when the previous step fails
      - name: inspect failed pods
        if: failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl describe pods --all-namespaces
      - name: cleanup
        if: always()
        run: make test/k8s/clean

  e2e-wasmedge:
    needs: [build]
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "check cgroup version"
        run: "mount | grep cgroup"
      - uses: actions/checkout@v3
      - name: setup rust-wasm target
        run: rustup target add wasm32-wasi
      - name: Setup OCI runtime build env
        run: ${GITHUB_WORKSPACE}/.github/scripts/build-linux.sh
        shell: bash
      - name: run
        run: make test/k3s
      - name: cleanup
        if: always()
        run: make test/k3s/clean
